# Generated by nixos-generate-config
{
  config,
  lib,
  pkgs,
  ...
}:

{
  networking.hostName = "klaptop";

  # Use iwd for networking
  networking.wireless.iwd.enable = true;

  # security.pki.certificateFiles = [ ./ucsd-ca.cer ];

  # Bluetooth (obviously)
  hardware.bluetooth.enable = true;

  # Logitech/Solaar
  hardware.logitech.wireless.enable = true;
  hardware.logitech.wireless.enableGraphical = true;

  # Autologin with greetd
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.greetd.greetd}/bin/agreety --cmd hyprland";
      };
      initial_session = {
        user = "kfish";
        command = "hyprland";
      };
    };
  };

  # Enable sway and let home-manager manager it
  # programs.sway.enable = true;
  # programs.sway.package = null;

  programs.hyprland.enable = true;

  # Set up Wireshark along with permissions
  programs.wireshark.enable = true;
  # Default module has an incorrect package name
  programs.wireshark.package = pkgs.wireshark;

  # Docker setup
  virtualisation.docker.enable = true;
  users.groups.docker.members = [ "kfish" ];

  #### The following code was generated by NixOS: ####
  # To mirror installer/scan/not-detected.nix
  hardware.enableRedistributableFirmware = true;

  # Use systemd-boot under UEFI
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f43c5b92-f6fb-4f10-a6ce-c8cc6bac5792";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0C25-528B";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
