name: Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check formatting
        run: nix fmt -- --check $(git ls-files '*.nix')

      - name: Evaluate configurations
        run: |
          for host in klaptop kdesktop wsl; do
            echo "::group::$host"
            nix eval --raw ".#nixosConfigurations.$host.config.system.build.toplevel.drvPath"
            echo
            echo "::endgroup::"
          done
